### ISSUE TITLE
2.3.3采访Christopher Rackauckas部分翻译可能不准确

### ISSUE THREAD

**Issue by terenceyjh** [JuliaCN/JuliaDataScience#30]
原翻译是“Chris 对这个请求感到非常惊讶，因为他从来没有期望能够将 GPU 计算与求解 ODE 结合起来。”，但是根据视频内容实际求解的不是有初始条件的ode，而是边界值问题的微分方程。使用gpu加速初值问题的微分方程求解应该是可以比较自然的用GPU加速的（都是矩阵和向量的乘法），此处应该指明是边界值问题

**Comment by findmyway** [comment]
非常感谢反馈！

方便的话可以直接修改 https://github.com/JuliaCN/JuliaDataScience/blob/main/contents/why_julia.md 发个PR么？

**Comment by guixinliu** [comment]
非常感谢您的指正！
我已通过 PR https://github.com/JuliaCN/JuliaDataScience/pull/31 修改。
